//-----------------------------------------------------------------------------
//  File Name:      app_isr1.h
//  Originator:     Delta PSBG Adv
//-----------------------------------------------------------------------------
#ifndef __APP_ISR1_H
#define __APP_ISR1_H

//-----------------------------------------------------------------------------
//  INCLUDES
//-----------------------------------------------------------------------------
#include "app_anpc_control.h"
#include "app_anpc_main.h"
#include "app_anpc_operation.h"
#include "app_physical_parameter.h"
#include "app_state.h"


//-----------------------------------------------------------------------------
//  DEFINES
//-----------------------------------------------------------------------------


//-----------------------------------------------------------------------------
//  VARIABLES
//-----------------------------------------------------------------------------


//-----------------------------------------------------------------------------
//  PRIVATE FUNCTIONS DEFINITION
//-----------------------------------------------------------------------------
//
// Lab1 ISR code
//
#pragma FUNC_ALWAYS_INLINE(isr1_RunLab1)
static inline void isr1_RunLab1(void)
{
    //
    // Read ADC sampled voltage and current values
    //
    phyvalue_ReadVoltageCurrentValues();

    PhyValue.IA.avg_pu = PhyValue.IA.raw_pu;
    PhyValue.IB.avg_pu = PhyValue.IB.raw_pu;
    PhyValue.IC.avg_pu = PhyValue.IC.raw_pu;

    //
    // Clear the PWM trips.
    //
    if(StateFlag.bits.pwm_kickoff == 1)
    {
        StateFlag.bits.pwm_kickoff = 0;
        pwm_mid_ClearAllPWMTrips();
    }

    if (StateFlag.bits.control_en == 1)
    {
        StateFlag.bits.control_en = 0;
        ctrl_Update3phasePWM(VICtrl.Duty_A, VICtrl.Duty_B, VICtrl.Duty_C,
                             VICtrl.Duty_A_prev, VICtrl.Duty_B_prev, VICtrl.Duty_C_prev);

        VICtrl.Duty_A_prev = VICtrl.Duty_A;
        VICtrl.Duty_B_prev = VICtrl.Duty_B;
        VICtrl.Duty_C_prev = VICtrl.Duty_C;
    }


    isr_mid_ClearPWMInterruptFlag(ISR_MID_ISR1_TRIG_BASE);
}

//
// Lab2 ISR code, no PLL, V/Hz control. No current control loop
//
#pragma FUNC_ALWAYS_INLINE(isr1_RunLab2)
static inline void isr1_RunLab2(void)
{
    //
    // Read ADC sampled voltage and current values
    //
    phyvalue_ReadVoltageCurrentValues();

    PhyValue.IA.avg_pu = PhyValue.IA.raw_pu;
    PhyValue.IB.avg_pu = PhyValue.IB.raw_pu;
    PhyValue.IC.avg_pu = PhyValue.IC.raw_pu;

    //
    // Clear the PWM trips when.
    //
    if(StateFlag.bits.pwm_kickoff == 1)
    {
        StateFlag.bits.pwm_kickoff = 0;
        pwm_mid_ClearAllPWMTrips();
        StateFlag.bits.control_en = 1;
    }

    if (StateFlag.bits.control_en == 1)
    {
        //
        // When grid is not connected, generate
        // internal phase reference
        //
        ctrl_GenerateInternalReference();

        //
        // Since this is Open-loop configuration, DQ values
        // generated by internal reference can be directly used
        // for generating 3-phase PWM duty values
        //
        VICtrl.Vd_pu = ANPC_VREF_DEFAULT;
        VICtrl.Vq_pu = 0;
        VICtrl.Vz_pu = 0;
        DQ0_ABC_run(&VICtrl.Vabc_pu, VICtrl.Vd_pu, VICtrl.Vq_pu, VICtrl.Vz_pu, Spll.sine, Spll.cosine);

        VICtrl.Duty_A = VICtrl.Vabc_pu.a;
        VICtrl.Duty_B = VICtrl.Vabc_pu.b;
        VICtrl.Duty_C = VICtrl.Vabc_pu.c;

        ctrl_Update3phasePWM(VICtrl.Duty_A, VICtrl.Duty_B, VICtrl.Duty_C,
                             VICtrl.Duty_A_prev, VICtrl.Duty_B_prev, VICtrl.Duty_C_prev);

        //
        // Run the SPLL module
        //
        ctrl_RunSPLL();

        //
        // Based on theta estimated by SPLL, compute sine and cosine
        //
        Spll.sine = sinf(Spll.angle_radians);
        Spll.cosine = cosf(Spll.angle_radians);
    }

    isr_mid_ClearPWMInterruptFlag(ISR_MID_ISR1_TRIG_BASE);
}

//
// Lab3 ISR code - No grid connection. I/Hz control for Inverter. Current control loop
// Use resistor load for inverter running in current control only
//
#pragma FUNC_ALWAYS_INLINE(isr1_RunLab3)
static inline void isr1_RunLab3(void)
{
    //
    // Read ADC sampled voltage and current values
    //
    phyvalue_ReadVoltageCurrentValues();

    PhyValue.IA.avg_pu = PhyValue.IA.raw_pu;
    PhyValue.IB.avg_pu = PhyValue.IB.raw_pu;
    PhyValue.IC.avg_pu = PhyValue.IC.raw_pu;

    //
    // Transform the above feedback signals from ABC to DQ axes
    //
    ctrl_ABCtoDQ0_Transform();

    //
    // Clear the PWM trips.
    //
    if(StateFlag.bits.pwm_kickoff == 1)
    {
        StateFlag.bits.pwm_kickoff = 0;
        pwm_mid_ClearAllPWMTrips();
        StateFlag.bits.control_en = 1;
    }

    if(StateFlag.bits.control_en == 1)
    {
        //
        // When grid is not connected, generate
        // internal phase reference
        //
        ctrl_GenerateInternalReference();

        //
        // Run the current close loop
        //
        ctrl_RunCurrentLoop();

        //
        // Vd and Vq can be directly used
        // for generating 3-phase PWM duty values
        DQ0_ABC_run(&VICtrl.Vabc_pu, VICtrl.Vd_pu, VICtrl.Vq_pu, VICtrl.Vz_pu, Spll.sine, Spll.cosine);

        VICtrl.Duty_A = VICtrl.Vabc_pu.a;
        VICtrl.Duty_B = VICtrl.Vabc_pu.b;
        VICtrl.Duty_C = VICtrl.Vabc_pu.c;

        ctrl_Update3phasePWM(VICtrl.Duty_A, VICtrl.Duty_B, VICtrl.Duty_C,
                             VICtrl.Duty_A_prev, VICtrl.Duty_B_prev, VICtrl.Duty_C_prev);

        VICtrl.Duty_A_prev = VICtrl.Duty_A;
        VICtrl.Duty_B_prev = VICtrl.Duty_B;
        VICtrl.Duty_C_prev = VICtrl.Duty_C;

        //
        // Run the SPLL module
        //
        ctrl_RunSPLL();

        PhyValue.Vbus.raw_pu = PhyValue.Vbusp.raw_pu + PhyValue.Vbusn.raw_pu;
        if(PhyValue.Vbus.raw_pu <= 0) // avoid division by zero
        {
            PhyValue.Vbus.raw_pu = 0.001;
        }
        PhyValue.Vbus.raw = PhyValue.Vbus.raw_pu * ANPC_VBUS_MAX_SENSE;
        PhyValue.Vbus.avg = PHY_LOW_PASS_FILTER * (PhyValue.Vbus.avg - PhyValue.Vbus.raw) + PhyValue.Vbus.raw;


        // Middle point voltage control
        PhyValue.Vbus_delta.raw = (PhyValue.Vbusp.raw_pu - PhyValue.Vbusn.raw_pu) * ANPC_VBUS_MAX_SENSE;
        PhyValue.Vbus_delta.avg = 0.9981 * (PhyValue.Vbus_delta.avg - PhyValue.Vbus_delta.raw) + PhyValue.Vbus_delta.raw;

        //AVG of the voltage
        //
        // Based on theta estimated by SPLL, compute sine and cosine
        //
        Spll.sine = sinf(Spll.angle_radians);
        Spll.cosine = cosf(Spll.angle_radians);
    }

    isr_mid_ClearPWMInterruptFlag(ISR_MID_ISR1_TRIG_BASE);
}

//
// Lab4 ISR code. Inverter mode. PLL with grid connection (so current loop only)
//
//
#pragma FUNC_ALWAYS_INLINE(isr1_RunLab4)
static inline void isr1_RunLab4(void)
{
    //
    // Read ADC sampled voltage and current values
    //
    phyvalue_ReadVoltageCurrentValues();

    PhyValue.IA.avg_pu = PhyValue.IA.raw_pu;
    PhyValue.IB.avg_pu = PhyValue.IB.raw_pu;
    PhyValue.IC.avg_pu = PhyValue.IC.raw_pu;

    //
    // Transform the above feedback signals from ABC to DQ axes
    //
    ctrl_ABCtoDQ0_Transform();

    if(AcValue.ac_A.zcd)
    {
        if(StateFlag.bits.pwm_kickoff == 1)
        {
            StateFlag.bits.pwm_kickoff = 0;
            pwm_mid_ClearAllPWMTrips();
            StateFlag.bits.control_en = 1;
        }
    }

    if (StateFlag.bits.control_en == 1)
    {
        //
        // Run the current close loop
        //
        ctrl_RunCurrentLoop();

        //
        // Vd and Vq can be directly used
        // for generating 3-phase PWM duty values
        DQ0_ABC_run(&VICtrl.Vabc_pu, VICtrl.Vd_pu, VICtrl.Vq_pu, VICtrl.Vz_pu, Spll.sine, Spll.cosine);

        // Middle point voltage control loop plus space vector for Inverter mode********
        VICtrl.Vbus_delta_out = CTRL_GV_RUN(&VICtrl.Vbus_delta, PhyValue.Vbus_delta.avg, 0);

        ctrl_3rd_Harmonic_Injection();

        VICtrl.Duty_A = VICtrl.Vabc_pu.a + VICtrl.Vbus_delta_out + VICtrl.Duty_3rd;
        VICtrl.Duty_B = VICtrl.Vabc_pu.b + VICtrl.Vbus_delta_out + VICtrl.Duty_3rd;
        VICtrl.Duty_C = VICtrl.Vabc_pu.c + VICtrl.Vbus_delta_out + VICtrl.Duty_3rd;

        ctrl_Update3phasePWM(VICtrl.Duty_A, VICtrl.Duty_B, VICtrl.Duty_C, 0, 0, 0);

        //
        // Update dead-band slew for soft-start of PFC
        //
        if(VICtrl.Deadband > ANPC_CTRL_HIGH_FREQ_DEADBAND)
        {
            pwm_mid_UpdatePWMDeadBand(VICtrl.Deadband);
            VICtrl.Deadband = VICtrl.Deadband - ANPC_SOFTSTART_DEADBAND_SLEW;
        }
        else
        {
            VICtrl.Deadband = ANPC_CTRL_HIGH_FREQ_DEADBAND;
            pwm_mid_UpdatePWMDeadBand(VICtrl.Deadband);
        }

    }

    //
    // Run SPLL
    //
    ctrl_RunSPLL();

    // Middle point voltage control
    PhyValue.Vbus_delta.raw = (PhyValue.Vbusp.raw_pu - PhyValue.Vbusn.raw_pu) * ANPC_VBUS_MAX_SENSE;
    PhyValue.Vbus_delta.avg = 0.9981 * (PhyValue.Vbus_delta.avg - PhyValue.Vbus_delta.raw) + PhyValue.Vbus_delta.raw;

    //
    // Based on theta estimated by SPLL, compute sine and cosine
    //
    Spll.sine = sinf(Spll.angle_radians);
    Spll.cosine = cosf(Spll.angle_radians);

    isr_mid_ClearPWMInterruptFlag(ISR_MID_ISR1_TRIG_BASE);
}

//
// Lab5 ISR code. PFC current loop only
//
#pragma FUNC_ALWAYS_INLINE(isr1_RunLab5)
static inline void isr1_RunLab5(void)
{
    //
    // Read ADC sampled voltage and current values
    //
    phyvalue_ReadVoltageCurrentValues();

    PhyValue.IA.avg_pu = PhyValue.IA.raw_pu;
    PhyValue.IB.avg_pu = PhyValue.IB.raw_pu;
    PhyValue.IC.avg_pu = PhyValue.IC.raw_pu;

    //
    // Transform the above feedback signals from ABC to DQ axes
    //
    ctrl_ABCtoDQ0_Transform();

    if (AcValue.ac_A.zcd)
    {
        if(StateFlag.bits.pwm_kickoff == 1)
        {
            StateFlag.bits.pwm_kickoff = 0;
            pwm_mid_ClearAllPWMTrips();
            StateFlag.bits.control_en = 1;
        }
    }

    if(StateFlag.bits.control_en == 1)
    {
        //
        // Run the current close loop
        //
        ctrl_RunCurrentLoop();

        //
        // Vd and Vq can be directly used for generating 3-phase PWM duty values
        //
        DQ0_ABC_run(&VICtrl.Vabc_pu, VICtrl.Vd_pu, VICtrl.Vq_pu, VICtrl.Vz_pu, Spll.sine, Spll.cosine);

        ctrl_3rd_Harmonic_Injection();

        //Middle point voltage control loop plus space vector for PFC mode*****
        VICtrl.Vbus_delta_out = CTRL_GV_RUN(&VICtrl.Vbus_delta, -PhyValue.Vbus_delta.avg, 0);

        VICtrl.Duty_A = VICtrl.Vabc_pu.a + VICtrl.Vbus_delta_out + VICtrl.Duty_3rd;
        VICtrl.Duty_B = VICtrl.Vabc_pu.b + VICtrl.Vbus_delta_out + VICtrl.Duty_3rd;
        VICtrl.Duty_C = VICtrl.Vabc_pu.c + VICtrl.Vbus_delta_out + VICtrl.Duty_3rd;

        // Middle point voltage control loop

        ctrl_Update3phasePWM(VICtrl.Duty_A, VICtrl.Duty_B, VICtrl.Duty_C, 0, 0, 0);

        //
        // Update dead-band slew for soft-start of PFC
        //
        if(VICtrl.Deadband > ANPC_CTRL_HIGH_FREQ_DEADBAND)
        {
            pwm_mid_UpdatePWMDeadBand(VICtrl.Deadband);
            VICtrl.Deadband = VICtrl.Deadband - ANPC_SOFTSTART_DEADBAND_SLEW;
        }
        else
        {
            VICtrl.Deadband = ANPC_CTRL_HIGH_FREQ_DEADBAND;
            pwm_mid_UpdatePWMDeadBand(VICtrl.Deadband);
        }

    }

    //
    // Run SPLL
    //
    ctrl_RunSPLL();

    // Middle point voltage calculation
    PhyValue.Vbus_delta.raw = (PhyValue.Vbusp.raw_pu - PhyValue.Vbusn.raw_pu) * ANPC_VBUS_MAX_SENSE;
    PhyValue.Vbus_delta.avg = 0.9981 * (PhyValue.Vbus_delta.avg - PhyValue.Vbus_delta.raw) + PhyValue.Vbus_delta.raw;


    //
    // Based on theta estimated by SPLL, compute sine and cosine
    //
    Spll.sine = sinf(Spll.angle_radians);
    Spll.cosine = cosf(Spll.angle_radians);

    isr_mid_ClearPWMInterruptFlag(ISR_MID_ISR1_TRIG_BASE);
}

//
// Lab6 ISR code. PFC voltage loop and current loop closed
//
#pragma FUNC_ALWAYS_INLINE(isr1_RunLab6)
static inline void isr1_RunLab6(void)
{
    //
    // Read ADC sampled voltage and current values
    //
    phyvalue_ReadVoltageCurrentValues();

    PhyValue.IA.avg_pu = PhyValue.IA.raw_pu;
    PhyValue.IB.avg_pu = PhyValue.IB.raw_pu;
    PhyValue.IC.avg_pu = PhyValue.IC.raw_pu;

    //
    // Transform the above feedback signals from ABC to DQ axes
    //
    ctrl_ABCtoDQ0_Transform();

    if (AcValue.ac_A.zcd)
    {
        if(StateFlag.bits.pwm_kickoff == 1)
        {
            StateFlag.bits.pwm_kickoff = 0;
            pwm_mid_ClearAllPWMTrips();
            StateFlag.bits.control_en = 1;
        }
    }

    if (StateFlag.bits.control_en == 1)
    {
        //
        // Run the current close loop
        //

        /* Voltage control loop */
        if (StateFlag.bits.soft_start_on == 1)
            VICtrl.Id_ref = VICtrl.Id_cmd; 
        else
            VICtrl.Id_ref = -1 * (CTRL_GV_RUN(&VICtrl.Vbus, VICtrl.Vbus_ref, PhyValue.Vbus.raw));

        /* Current control loop */
        ctrl_RunCurrentLoop();

        /* Middle point voltage control loop */
        VICtrl.Vbus_delta_out = CTRL_GV_RUN(&VICtrl.Vbus_delta, -PhyValue.Vbus_delta.avg, 0);

        /*
         * Vd and Vq can be directly used for generating 3-phase PWM duty values.
         */
        DQ0_ABC_run(&VICtrl.Vabc_pu, VICtrl.Vd_pu, VICtrl.Vq_pu, VICtrl.Vz_pu, Spll.sine, Spll.cosine);

        ctrl_3rd_Harmonic_Injection();

        /*
         * Constant duty has been added in the system in order to perturb the middle point of the converter.
         */
        VICtrl.Duty_A = VICtrl.Vabc_pu.a + VICtrl.Vbus_delta_out + 0;// VICtrl.Duty_3rd;
        VICtrl.Duty_B = VICtrl.Vabc_pu.b + VICtrl.Vbus_delta_out + 0;// VICtrl.Duty_3rd;
        VICtrl.Duty_C = VICtrl.Vabc_pu.c + VICtrl.Vbus_delta_out + 0;// VICtrl.Duty_3rd;


        ctrl_Update3phasePWM(VICtrl.Duty_A, VICtrl.Duty_B, VICtrl.Duty_C, 0, 0, 0);

        //
        // Update dead-band slew for soft-start of PFC
        //
        if(0)//VICtrl.Deadband > ANPC_CTRL_HIGH_FREQ_DEADBAND)
        {
            pwm_mid_UpdatePWMDeadBand(VICtrl.Deadband);
            VICtrl.Deadband = VICtrl.Deadband - ANPC_SOFTSTART_DEADBAND_SLEW;
        }
        else
        {
            VICtrl.Deadband = ANPC_CTRL_HIGH_FREQ_DEADBAND;
            pwm_mid_UpdatePWMDeadBand(VICtrl.Deadband);
        }

    }

    /* Run SPLL */
    ctrl_RunSPLL();

    /* AVG of the voltage */
    PhyValue.Vbus_delta.raw = (PhyValue.Vbusp.raw_pu - PhyValue.Vbusn.raw_pu) * ANPC_VBUS_MAX_SENSE;
    PhyValue.Vbus_delta.avg = 0.9981 * (PhyValue.Vbus_delta.avg - PhyValue.Vbus_delta.raw) + PhyValue.Vbus_delta.raw;

    /*
     * Based on theta estimated by SPLL, compute sine and cosine.
     */
    Spll.sine = sinf(Spll.angle_radians);
    Spll.cosine = cosf(Spll.angle_radians);

    isr_mid_ClearPWMInterruptFlag(ISR_MID_ISR1_TRIG_BASE);
}

#pragma FUNC_ALWAYS_INLINE(ISR1_Callback)
static inline void ISR1_Callback(void)
{

    #if ANPC_LAB == 1U
        isr1_RunLab1();

    #elif  ANPC_LAB == 2U //Inverter open loop, no PLL, V/Hz control. No current control loop
        isr1_RunLab2();

    #elif  ANPC_LAB == 3U // Inverter closed current loop without PLL (no grid connection. Resistive load)
        isr1_RunLab3();

    #elif  ANPC_LAB == 4U  // Inverter closed current loop with PLL (grid connected mode)
        isr1_RunLab4();

    #elif  ANPC_LAB == 5U // PFC Current loop with open voltage loop
        isr1_RunLab5();

    #elif  ANPC_LAB == 6U // PFC Voltage loop and Current loop closed
        isr1_RunLab6();

    #endif

}







#endif
